[package]
name = "advent_of_code_2022"
version = "0.1.0"
edition = "2021"

[dependencies]
neofiglet = "0.1.1"
text_io = "0.1.12"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "benchmark"
harness = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
